# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Endor Labs
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '27 17 * * 6'
jobs:
  scan:
    permissions:
      security-events: write # Used to upload sarif artifact to GitHub
      contents: read # Used to checkout a private repository by actions/checkout.
      actions: read # Required for private repositories to upload sarif files. GitHub Advanced Security licenses are required.
      id-token: write # Used for keyless authentication to Endor Labs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    #### Package Build Instructions
    ### Use this section to define the build steps used by your software package.
    ### Endor Labs builds your software for you where possible but the required build tools must be made available.
    # - name: Setup Java
    #   uses: actions/setup-java@v4
    #   with:
    #     distribution: 'microsoft'
    #     java-version: '17'
    # - name: Build Package
    #   run: mvn clean install
    - name: Endor Labs scan pull request
      uses: endorlabs/github-action@v1.1.6
      with:
        namespace: "darren-learn" # Modify the namespace to your Endor Labs tenant namespace.
        scan_secrets: true
        scan_dependencies: true
        additional_args: "--prune-invalid-paths"
        # sarif_file: findings.sarif
    # - name: Upload SARIF to github
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: findings.sarif
